/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/island.glb --output src/models/Island_new.jsx --types 
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCube11_rocks1_0: THREE.Mesh
    polySurface944_tree_body_0: THREE.Mesh
    polySurface945_tree1_0: THREE.Mesh
    polySurface946_tree2_0: THREE.Mesh
    polySurface947_tree1_0: THREE.Mesh
    polySurface948_tree_body_0: THREE.Mesh
    polySurface949_tree_body_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/island.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube11_rocks1_0.geometry} material={materials.PaletteMaterial001} />
      <instancedMesh args={[nodes.polySurface944_tree_body_0.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.polySurface944_tree_body_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface945_tree1_0.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.polySurface945_tree1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface946_tree2_0.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.polySurface946_tree2_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface947_tree1_0.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.polySurface947_tree1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface948_tree_body_0.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.polySurface948_tree_body_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface949_tree_body_0.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.polySurface949_tree_body_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/island.glb')
